### PR TITLE
Fix for some some BSD and macOS that may lack poll

### LINKED ISSUE #32: wulitzer fires an exception on macOS and probably any BSD-like system
macOS and BSD systems lack `select.poll`:

```
File "/Users/admin/src/wurlitzer/wurlitzer.py", line 179, in forwarder
    poller = select.poll()
AttributeError: module 'select' has no attribute 'poll'
```

### PR DESCRIPTION
**Pull request by Mottl**
This PR fixes #32 for macOS and BSD systems by supporting the `kqueue` additionally to the `pool`.

### CODE REVIEW

**Comment by Mottl** [comment]
@minrk, please review

**Comment by minrk** [comment]
This doesn't appear to be accurate. This package was first developed on macOS and FreeBSD and the tests are run on mac on Travis, so select.poll definitely works there. Can you give more detail on where select.poll does not exist? The comments on the conditions are at least not accurate.

**Comment by Mottl** [comment]
I use python 3.7 from Macports on macOS 10.13.

```
$ ipython
Python 3.7.4 (default, Jul 11 2019, 01:07:24) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.6.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import select                                                                                                                      

In [2]: select.poll()                                                                                                                      
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-d4092895c2d7> in <module>
----> 1 select.poll()

AttributeError: module 'select' has no attribute 'poll'
```


Here is other a discussion about `poll` on macOS:
https://stackoverflow.com/questions/19740471/cannot-use-python-select-poll-in-mac-os

**Comment by Mottl** [comment]
> This package was first developed on macOS and FreeBSD

yes, but `select.poll()` was introduced only on 2018-12-07 by 8d2e997d

**Comment by Mottl** [comment]
@minrk, ping

**Comment by reneeotten** [comment]
@Mottl @minrk I have experienced the same issue when attempting to update the ```wurlitzer``` package in MacPorts; see the discussion [here](https://trac.macports.org/ticket/58831).

Just as Apple does with their system ```python```, in MacPorts we disable ```poll``` as there were runtime issues with ```poll``` on macOS versions in the past. It's probably worth looking into which macOS/Python versions were affected and if that underlying problem is indeed resolved we could perhaps re-enable ```poll``` there. For example, in ```conda``` it appears that ```select.poll()``` is available (that probably adds to the confusion); but the fact that it's present does not necessarily mean that it is not affected by runtime errors.

Alternatively, it might be better to move away from ```select.poll()``` if possible since that would circumvent all possible issues on macOS and improve portability (I note that the Python documentation also states that "select.poll - (Not supported by all operating systems.)".

**Comment by jmroot** [comment]
The Right Way is probably to just use `selectors.DefaultSelector` rather than relying on any particular implementation. If you care about old python versions, there's a backport called `selectors2` on pypi.

**Comment by minrk** [comment]
@jmroot thanks! That sounds perfect. It would be great to switch to selectors.DefaultSelector and a conditional dependency on selectors2 on Python <3.4.

I was planning to merge this once I refactored it a little to have less duplicate code in branches and switch at an abstract level, but selectors is exactly that.

@Mottl If you could make the above changes to use selectors.DefaultSelector instead, I'll be happy to merge.

**Pull request closed without merging**
